---
title: "git_00"
author: "Estevan Green"
date: "Year 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
A short direction

To avoid dejection,

By variations

In occupations, 

And prolongation 

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
A boat, beneath a sunny sky

Lingering onward dreamily

In an evening of July

Children three that nestle near,

Eager eye and willing ear,

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,

Shining with all his might:

He did his very best to make

The billows smooth and bright 

And this was odd, because it was

 The middle of the night.

The moon was shining sulkily,

Because she thought the sun

Had got no business to be there

After the day was done —

"It's very rude of him," she said,

"To come and spoil the fun."

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
In twilight's embrace, stars dance above,

Whispering secrets through celestial love.

A moonlit path weaves through silvered trees,

Guiding hearts that yearn, setting spirits free.

Soft whispers of breeze carry dreams on air,

As night's gentle embrace we both shall share.

Within this verse, a fleeting glimpse of grace,

A timeless moment, our souls embrace.

